"""setup delete cascades

Revision ID: 22f5905eaa83
Revises: e3b24191a8b8
Create Date: 2021-08-02 11:42:36.326899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f5905eaa83'
down_revision = 'e3b24191a8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colony_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('colony_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['colony_id'], ['colony.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('colony', 'coral_species_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('colony', 'dive_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('colony_coral_species_id_fkey', 'colony', type_='foreignkey')
    op.drop_constraint('colony_dive_id_fkey', 'colony', type_='foreignkey')
    op.create_foreign_key(None, 'colony', 'coral_species', ['coral_species_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'colony', 'dive', ['dive_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dive_site_id_fkey', 'dive', type_='foreignkey')
    op.create_foreign_key(None, 'dive', 'site', ['site_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('site_region_id_fkey', 'site', type_='foreignkey')
    op.create_foreign_key(None, 'site', 'region', ['region_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.create_foreign_key('site_region_id_fkey', 'site', 'region', ['region_id'], ['id'])
    op.drop_constraint(None, 'dive', type_='foreignkey')
    op.create_foreign_key('dive_site_id_fkey', 'dive', 'site', ['site_id'], ['id'])
    op.drop_constraint(None, 'colony', type_='foreignkey')
    op.drop_constraint(None, 'colony', type_='foreignkey')
    op.create_foreign_key('colony_dive_id_fkey', 'colony', 'dive', ['dive_id'], ['id'])
    op.create_foreign_key('colony_coral_species_id_fkey', 'colony', 'coral_species', ['coral_species_id'], ['id'])
    op.alter_column('colony', 'dive_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('colony', 'coral_species_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('colony_photo')
    # ### end Alembic commands ###
