"""first many_to_many table campaign_user

Revision ID: 3cf2c4a56b74
Revises: 90759d94e181
Create Date: 2021-08-02 12:28:09.787038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf2c4a56b74'
down_revision = '90759d94e181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_user',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'user_id')
    )
    op.add_column('campaign', sa.Column('ncbi_bio_project_accession', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'ncbi_bio_project_accession')
    op.drop_table('campaign_user')
    # ### end Alembic commands ###
