"""setup campagin, divetable

Revision ID: 90759d94e181
Revises: 22f5905eaa83
Create Date: 2021-08-02 12:00:41.020495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90759d94e181'
down_revision = '22f5905eaa83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('lead_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diver_table_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dive_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diver_table_photo')
    op.drop_table('campaign')
    # ### end Alembic commands ###
