"""add ncbi fields to environment_record

Revision ID: 9e5fac321a22
Revises: 9c5cfbf15b44
Create Date: 2021-08-13 13:57:54.219864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5fac321a22'
down_revision = '9c5cfbf15b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment_record', sa.Column('env_broad_scale', sa.String(length=100), nullable=False))
    op.add_column('environment_record', sa.Column('env_local_scale', sa.String(length=100), nullable=False))
    op.add_column('environment_record', sa.Column('env_medium', sa.String(length=100), nullable=False))
    op.add_column('site', sa.Column('abbreviation', sa.String(length=10), nullable=False))
    op.alter_column('site', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('site_abbreviation_code_key', 'site', type_='unique')
    op.create_unique_constraint(None, 'site', ['abbreviation'])
    op.drop_column('site', 'env_broad_scale')
    op.drop_column('site', 'env_medium')
    op.drop_column('site', 'env_local_scale')
    op.drop_column('site', 'abbreviation_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('abbreviation_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('env_local_scale', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('env_medium', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('env_broad_scale', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'site', type_='unique')
    op.create_unique_constraint('site_abbreviation_code_key', 'site', ['abbreviation_code'])
    op.alter_column('site', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('site', 'abbreviation')
    op.drop_column('environment_record', 'env_medium')
    op.drop_column('environment_record', 'env_local_scale')
    op.drop_column('environment_record', 'env_broad_scale')
    # ### end Alembic commands ###
