"""rename user.register_date user.registration_date

Revision ID: a155d5b1e457
Revises: cc90f53694ec
Create Date: 2021-07-29 15:12:18.470569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a155d5b1e457'
down_revision = 'cc90f53694ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_date', sa.Date(), nullable=True))
    op.drop_column('user', 'register_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('user', 'registration_date')
    # ### end Alembic commands ###
