"""tweaks during site testing

Revision ID: a279ebe7ac5c
Revises: 9e5fac321a22
Create Date: 2021-08-13 16:05:45.204709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a279ebe7ac5c'
down_revision = '9e5fac321a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('name_abbreviation', sa.String(length=10), nullable=False))
    op.add_column('site', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('site', sa.Column('country_abbreviation', sa.String(length=2), nullable=True))
    op.add_column('site', sa.Column('sub_region', sa.String(length=200), nullable=True))
    op.drop_constraint('site_abbreviation_key', 'site', type_='unique')
    op.create_unique_constraint(None, 'site', ['name_abbreviation'])
    op.create_unique_constraint(None, 'site', ['country_abbreviation'])
    op.drop_column('site', 'abbreviation')
    op.drop_column('site', 'geo_loc_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('geo_loc_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('site', sa.Column('abbreviation', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.create_unique_constraint('site_abbreviation_key', 'site', ['abbreviation'])
    op.drop_column('site', 'sub_region')
    op.drop_column('site', 'country_abbreviation')
    op.drop_column('site', 'country')
    op.drop_column('site', 'name_abbreviation')
    # ### end Alembic commands ###
