"""add assay constant params to cbass assay

Revision ID: afe6c682f907
Revises: 8f98bf9dd766
Create Date: 2021-08-16 15:42:01.717804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe6c682f907'
down_revision = '8f98bf9dd766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
