"""make coral_species, site, region, dive and colony tables

Revision ID: e3b24191a8b8
Revises: a155d5b1e457
Create Date: 2021-08-02 10:48:53.775176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b24191a8b8'
down_revision = 'a155d5b1e457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coral_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phylum_tax', sa.String(length=50), nullable=True),
    sa.Column('class_tax', sa.String(length=50), nullable=True),
    sa.Column('order_tax', sa.String(length=50), nullable=True),
    sa.Column('family_tax', sa.String(length=50), nullable=True),
    sa.Column('genus_tax', sa.String(length=50), nullable=True),
    sa.Column('species_monomial_tax', sa.String(length=50), nullable=True),
    sa.Column('species_binomial_tax', sa.String(length=100), nullable=True),
    sa.Column('ncbi_tax_id', sa.Integer(), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation_code', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('time_zone', sa.Integer(), nullable=False),
    sa.Column('geo_loc_name', sa.String(length=100), nullable=False),
    sa.Column('env_broad_scale', sa.String(length=100), nullable=False),
    sa.Column('env_local_scale', sa.String(length=100), nullable=False),
    sa.Column('env_medium', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('time_in', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('time_out', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('max_depth', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=2, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coral_species_id', sa.Integer(), nullable=True),
    sa.Column('dive_id', sa.Integer(), nullable=True),
    sa.Column('time_collected', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('depth_collected', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['coral_species_id'], ['coral_species.id'], ),
    sa.ForeignKeyConstraint(['dive_id'], ['dive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'registration_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'registration_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('colony')
    op.drop_table('dive')
    op.drop_table('site')
    op.drop_table('region')
    op.drop_table('coral_species')
    # ### end Alembic commands ###
