"""sea_water_source -> seawater_source

Revision ID: e4fb975e5518
Revises: afe6c682f907
Create Date: 2021-08-16 15:48:56.463734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4fb975e5518'
down_revision = 'afe6c682f907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cbass_assay', sa.Column('flow_rate_liters_per_hour', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('cbass_assay', sa.Column('light_level', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('cbass_assay', sa.Column('tank_volumne_liter', sa.Integer(), nullable=True))
    op.add_column('cbass_assay', sa.Column('seawater_source', sa.String(length=50), nullable=True))
    op.drop_column('heat_stress_profile', 'sea_water_source')
    op.drop_column('heat_stress_profile', 'light_level')
    op.drop_column('heat_stress_profile', 'tank_volumne_liter')
    op.drop_column('heat_stress_profile', 'flow_rate_liters_per_hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heat_stress_profile', sa.Column('flow_rate_liters_per_hour', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('heat_stress_profile', sa.Column('tank_volumne_liter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('heat_stress_profile', sa.Column('light_level', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('heat_stress_profile', sa.Column('sea_water_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('cbass_assay', 'seawater_source')
    op.drop_column('cbass_assay', 'tank_volumne_liter')
    op.drop_column('cbass_assay', 'light_level')
    op.drop_column('cbass_assay', 'flow_rate_liters_per_hour')
    # ### end Alembic commands ###
